repos:
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
        - id: black
    - repo: local
      hooks:
        - id: pylint
          name: pylint
          entry: python lint.py -p ../OXYGEN-CS-GRP2-EQ1/src
          language: system
          always_run: true
          pass_filenames: false
        - id: pytest
          name: pytest
          entry: pytest
          language: system
          always_run: true
          pass_filenames: false