version: "3"
services:
    db:
        platform: linux/x86_64
        container_name: mydb
        image: mysql:5.7
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
    app:
        container_name: oxygen-cs-grp2-eq1-app
        links:
            - "db"
        build: ./
        ports:
            - "5001:5000"