name: Docker Image CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      database_name: oxygenCsGrp2Eq1E23Db
      database_user: root
      database_password: root

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.9'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install black pytest pylint requests signalrcore python-dotenv mysql-connector-python
          pip install --user pipenv
          pipenv install
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
    - name: Verify MySQL connection from host
      run: |
        sudo apt-get install -y mysql-client
        mysql --host localhost --port 3306 -u${{ env.database_user }} -p${{ env.database_password }} -e "SHOW DATABASES"
    - name: Test with pytest
      run:  |
          pipenv run test
    - name: Analyse de code statique et de formatage
      run:  |
          black .
          python lint.py -p src 
    - name: build docker image
      run:  |
          docker build . --file Dockerfile --tag oxygen-cs-grp02-eq1:$(date +%s)
